2024-11-11 10:10:01,665, WARNING, Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "D:\Disc D\Program Files\PyCharm Community Edition 2024.1.4\My projects\Urban-1st\Module 12\tests_12_4.py", line 26, in test_run
    runner = module_12_4.Runner(1, 5)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Disc D\Program Files\PyCharm Community Edition 2024.1.4\My projects\Urban-1st\Module 12\module_12_4.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-11-11 10:10:01,666, WARNING, Неверная скорость для Runner
Traceback (most recent call last):
  File "D:\Disc D\Program Files\PyCharm Community Edition 2024.1.4\My projects\Urban-1st\Module 12\tests_12_4.py", line 12, in test_walk
    runner = module_12_4.Runner("Alex", -5)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Disc D\Program Files\PyCharm Community Edition 2024.1.4\My projects\Urban-1st\Module 12\module_12_4.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
